prompts = {
    "intro": [
        "Hello! Welcome to Nella's song recommendation system! We can recommend you songs from spotify based on their metrics. Let's get started building you a playlist!",
        "Hi there! Welcome to Nella's song recommendation system! We're here to curate a personalized playlist for you based on Spotify's metrics. Let's begin creating your ultimate music collection!",
        "Greetings! You've entered Nella's song recommendation system! We're here to suggest you some amazing tracks from Spotify, using their advanced metrics. Let's embark on a musical journey and build your perfect playlist!",
        "Welcome! You've arrived at Nella's song recommendation system! We're equipped to offer you top-notch song suggestions from Spotify, leveraging their powerful metrics. Let's dive in and craft an incredible playlist just for you!",
        "Hey there! Nella's song recommendation system extends a warm welcome to you! We specialize in recommending songs from Spotify, using their comprehensive metrics. Let's kick off your playlist-building adventure!",
        "Greetings and salutations! Step into Nella's song recommendation system, where we excel at suggesting Spotify songs based on their intricate metrics. Let's commence the journey of creating your dream playlist!",
        "Welcome, music lover! You've arrived at Nella's song recommendation system, your gateway to discovering incredible songs on Spotify. Get ready to embark on a playlist-building extravaganza!",
        "Hello and welcome! Nella's song recommendation system is at your service, ready to recommend you fantastic tunes from Spotify's vast collection. Let's jump right in and create your ultimate playlist!",
        "Hey, music enthusiast! Welcome to Nella's song recommendation system, your go-to source for discovering great songs from Spotify. Let's kickstart the process of curating your perfect playlist!",
        "Greetings, fellow music aficionado! Nella's song recommendation system is here to assist you in finding amazing songs from Spotify, leveraging their powerful metrics. Let's commence the playlist-building journey!",
        "Hello, music lover! Welcome to Nella's song recommendation system, where we specialize in handpicking top tracks from Spotify based on their metrics. Let's embark on a musical adventure and craft your dream playlist!",
        "Hey there, fellow music enthusiast! Step into Nella's song recommendation system, your one-stop destination for discovering incredible songs from Spotify. Let's dive in and start building your ultimate playlist!",
        "Welcome to Nella's song recommendation system! We're thrilled to have you here. Get ready to explore Spotify's vast collection of songs as we curate a personalized playlist just for you!",
        "Greetings, music aficionado! You've entered Nella's song recommendation system, where we utilize Spotify's metrics to suggest the perfect songs for your playlist. Let's begin crafting a musical masterpiece!",
        "Hello and welcome! Nella's song recommendation system is at your service, offering you an exceptional playlist-building experience with Spotify's finest tracks. Let's get started and create your musical haven!",
        "Hey, music lover! Welcome to Nella's song recommendation system, the ultimate destination for discovering amazing songs on Spotify. Let's embark on a journey of musical exploration and create your ideal playlist!",
        "Greetings, fellow music aficionado! Nella's song recommendation system is here to guide you through the vast realm of Spotify, suggesting songs that align perfectly with your tastes. Let's begin the playlist-building process!",
        "Welcome to Nella's song recommendation system! We're excited to introduce you to Spotify's finest tunes, carefully selected based on their metrics. Let's start building an extraordinary playlist together!",
        "Hello there, music enthusiast! Nella's song recommendation system is here to elevate your music experience with handpicked songs from Spotify's extensive library. Let's kick off your personalized playlist journey!",
        "Hey, music lover! Welcome to Nella's song recommendation system, your gateway to an exceptional collection of songs on Spotify. Let's dive in and create a playlist that resonates with your unique taste!",
        "Greetings and salutations! Step into Nella's song recommendation system, where we bring you the best of Spotify's music catalog, tailored to your preferences. Let's kickstart the playlist creation process and make some musical magic happen!"
    ],
    "explicit": [
        "Are you okay with listening to explicit music?",
        "Are you comfortable with explicit music?",
        "Is it acceptable for you to listen to explicit music?",
        "Would it be okay if we recommend you explicit music?",
        "Are you open to listening to explicit content in music?",
        "Are you fine with explicit lyrics in the music you listen to?",
        "Is it alright with you if we include explicit songs?",
        "Are you okay with songs that contain explicit language?",
        "Are you comfortable with listening to music that contains explicit content?",
        "Are you fine with songs that may contain explicit language or adult themes?",
        "Would you be open to listening to music that includes explicit content?",
        "Is it acceptable for you to listen to music that has explicit lyrics or mature themes?",
        "Are you okay with songs that contain explicit lyrics or explicit references?",
        "Is it acceptable for you to be recommended music that includes explicit language or explicit imagery?"
    ],
    "popularity": [
        "Would you like the most popular results? If not, the results will be sorted by how well they match your responses.",
        "Are you interested in seeing the most popular results? If not, we can prioritize results based on how well they match your responses.",
        "Do you prefer to view the most popular results? Otherwise, we can prioritize results based on their relevance to your responses.",
        "Would you like to prioritize the most popular results? If not, we can sort the results based on how well they align with your responses.",
        "Are you inclined to see the most popular results? Alternatively, we can sort the results based on their alignment with your responses.",
        "Do you want the results to be sorted by popularity? If not, we can prioritize results based on how closely they match your responses.",
        "Are you keen on seeing the most popular results? If not, we can prioritize results based on their relevance to your responses.",
        "Would you prefer the most popular results? Otherwise, we can sort the results based on how well they match your responses.",
        "Are you interested in a popularity-based sorting of results? If not, we can prioritize results based on their alignment with your responses.",
        "Do you want to see the most popular results? If not, we can sort the results based on how closely they align with your responses.",
        "Are you open to viewing the most popular results? Alternatively, we can prioritize results based on how well they align with your responses.",
        "Should we prioritize the most popular results? If not, we will sort them based on how well they match your responses.",
        "Would you like us to prioritize the most popular results? Otherwise, we can sort them based on their relevance to your responses.",
        "Are you interested in seeing the most popular results first? If not, we can prioritize results based on how well they align with your responses.",
        "Do you prefer the most popular results? If not, we can sort the results based on how closely they match your responses.",
        "Should we give priority to the most popular results? If not, we will sort the results based on their alignment with your responses.",
        "Would you like the results to be sorted by popularity? If not, we can prioritize results based on how closely they match your responses.",
        "Are you inclined to see the most popular results? Alternatively, we can sort the results based on their relevance to your responses.",
        "Should we consider the popularity of the results? If not, we will prioritize them based on how well they match your responses.",
        "Do you want us to factor in popularity when sorting the results? If not, we can prioritize them based on their alignment with your responses.",
        "Would you like us to consider a popularity-based sorting of results? If not, we will prioritize them based on how closely they align with your responses."
    ],
    "specifics": [
        "Would you like to listen to any specific artist, album, song, or genres? If a specific song is given, similar songs for you to listen to will be recommended.",
        "Do you have any particular artist, album, song, or genres in mind that you would like to listen to? If you provide a specific song, we can recommend similar songs for you.",
        "Are there any specific artists, albums, songs, or genres that you would like to listen to? If you mention a particular song, we can suggest similar songs for you.",
        "Would you like to specify any artist, album, song, or genres for your listening preferences? If you provide a specific song, we can offer recommendations for similar songs.",
        "Do you have any preferences for artist, album, song, or genres that you would like to listen to? If you mention a specific song, we can provide suggestions for similar songs.",
        "Are there any particular artists, albums, songs, or genres that you would like to explore? If you mention a specific song, we can guide you to similar songs.",
        "Would you like to indicate any specific artist, album, song, or genres that you are interested in? If you provide a particular song, we can propose similar songs for your listening pleasure.",
        "Do you have any favorite artists, albums, songs, or genres that you would like to listen to? If you mention a specific song, we can recommend similar songs to enhance your music experience.",
        "Are there any specific musicians, albums, tracks, or genres that you want to listen to? If you provide a particular song, we can suggest similar songs for your enjoyment.",
        "Would you like to specify any particular artist, album, song, or genres that you want to explore? If you mention a specific song, we can provide recommendations for similar songs.",
        "Do you have any preferences for artist, album, song, or genres that you would like to explore? If you mention a particular song, we can suggest similar songs for you.",
        "Are there any specific musicians, albums, tracks, or genres that you would like to hear? If you mention a specific song, we can recommend similar songs for your listening pleasure.",
        "Would you like to indicate any favorite artist, album, song, or genres that you want to listen to? If you provide a particular song, we can suggest similar songs for your enjoyment.",
        "Do you have any preferred artists, albums, songs, or genres that you would like to explore? If you mention a specific song, we can guide you to similar songs.",
        "Are there any specific artists, albums, songs, or genres that you are interested in listening to? If you mention a particular song, we can provide recommendations for similar songs.",
        "Would you like to specify any favorite artist, album, song, or genres that you want to listen to? If you provide a specific song, we can suggest similar songs for your music selection.",
        "Do you have any particular artists, albums, songs, or genres in mind that you would like to explore? If you mention a specific song, we can recommend similar songs for your listening pleasure.",
        "Are there any specific musicians, albums, tracks, or genres that you would like to include in your music selection? If you mention a particular song, we can guide you to similar songs.",
        "Would you like to indicate any preferred artist, album, song, or genres that you want to listen to? If you provide a specific song, we can suggest similar songs for your music enjoyment.",
        "Do you have any specific artists, albums, songs, or genres that you would like to listen to? If you mention a particular song, we can provide recommendations for similar songs.",
        "Are there any preferred artists, albums, songs, or genres that you would like to explore? If you mention a specific song, we can suggest similar songs for your music selection."
    ]
}